server:
  port: 8090
  
spring:
  application:
    name: spring-cloud-test-provider-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/shashou?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 123456
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 4000
top:
  lemna:
    validate:
      code:
        sms:
          url: /merchant/merchant
    oss:
      aliyun:
        accessId: LTAIbOsGV5flHOPI
        accessKey: MuTwSUsSpcDzqo11tt3Iih1b8Oxqon
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: shashou-public
        dir: tmp